# dataset configs
dataset_cfg:
  dataset_type: PowerUAV
  data_root_dir: /workspace/data/KITTI_Tracking/ #/dataset/KITTI_Tracking/
  num_points: 1024  # Number of input points
  num_classes: 6
  sub_grid_size: 0.06  # preprocess_parameter
  

# model configs
model_cfg:
  model_type: DGCNN
  num_classes: 5 # the number of valid classes: len(all_labels)- len(ignored_labels)
  ignored_labels: [0]
  all_labels: [0, 1, 2, 3, 4, 5]
  emb_dims: 1024
  dropout: 0.5
  k: 20

# task configs
task_type: SegTask
#missing_threshold: 0.2

# optimizer & scheduler configs
optimizer_cfg:
  optimizer_type: Adam
  lr: 0.01
  weight_decay: 0
  betas: [0.5, 0.999]
  eps: 1.0e-6

scheduler_cfg:
  scheduler_type: StepLR
  step_size: 20
  gamma: 0.1

# loss configs
loss_cfg:
  ce_weight: 1.0


# train & eval configs
train_cfg:
  max_epochs: 100
  train_steps: 10000  # Number of steps per epochs
  batch_size: 6
  num_workers: 4
  save_per_epoch: 40
  save_top_k: 5
  val_per_epoch: 1

eval_cfg:
  batch_size: 1
  num_workers: 4